// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AudioPlayer is an autogenerated mock type for the AudioPlayer type
type AudioPlayer struct {
	mock.Mock
}

// PlayAudio provides a mock function with given fields: audio
func (_m *AudioPlayer) PlayAudio(audio []byte) {
	_m.Called(audio)
}
